## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # 2018-02-15 Erik Schnetter: Installing HDF5 via Homebrew is broken;
  # there is a weird conflict that prevents GCC 7.3 from being
  # installed.
  # - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

# uncomment and modify the following lines to manually install system packages
addons:
  # apt-get for linux
  apt:
    packages:
      - hdf5-tools
before_script:
  # homebrew for mac
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install hdf5; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("CleanEOSTable"); Pkg.test("CleanEOSTable"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("CleanEOSTable")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("CleanEOSTable")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
